---
  title: "Cost-Effectiveness Comparison"
  author: "Nathan Green"
  date: "Dec 2017"
  output:
  word_document:
  keep_md: yes
  editor_options:
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r , fig.width=9, fig.height=9}

library(IDEAdectree)
library(BCEA)
library(ggplot2)

data("TBdata_clinical_cleaned", package = "IDEAdectree")
data('drug_dose-cost', package = "IDEAdectree")
data("costs", package = "VANTDET")
data("time_res", package = "VANTDET")
data("performance", package = "VANTDET")

date.diff <- datc.diff <- list()
dat.ceac20000 <- dat.ceac30000 <- NA
dat <- list()

QUANT <- 0.5  #0.65
yearindays <- 365
WTP <- c(20000, 30000)/yearindays
```

```{r dectree, fig.width=9, fig.height=9, fig.keep='all'}

dat1 <- dectree(data = data,
                           name.ruleout = "TSPOT",
                           SPEC = TSPOT.noIndet.spec.mean,
                           SENS = TSPOT.noIndet.sens.mean,
                           SPECvar = TSPOT.noIndet.spec.var,
                           SENSvar = TSPOT.noIndet.sens.var)

dat2 <- dectree(data = data,
                           name.ruleout = "TSPOT",
                           SPEC = TSPOT.HIV.noIndet.spec.mean,
                           SENS = TSPOT.HIV.noIndet.sens.mean,
                           SPECvar = TSPOT.HIV.noIndet.spec.var,
                           SENSvar = TSPOT.HIV.noIndet.sens.var)

dat3 <- dectree(data = data,
                           name.ruleout = "TSPOT",
                           SPEC = TSPOT.HIVneg.noIndet.spec.mean,
                           SENS = TSPOT.HIVneg.noIndet.sens.mean,
                           SPECvar = TSPOT.HIVneg.noIndet.spec.var,
                           SENSvar = TSPOT.HIVneg.noIndet.sens.var)

dat$e <- cbind(dat1$e, dat2$e[ ,2], dat3$e[ ,2])
dat$c <- cbind(dat1$c, dat2$c[ ,2], dat3$c[ ,2])

intlabels <- c("Current",
               "Enhanced TSPOT: All, no Indets",
               "Enhanced TSPOT: HIV positive, no Indets",
               "Enhanced TSPOT: HIV negative, no Indets")
```

```{r CE-plane, fig.width=9, fig.height=9, fig.keep='all'}

my.plot.bcea(dat1, dat2, dat3, wtp = WTP,
             intlabels = intlabels,
             wtpNEG = "Y")

my.plot.bcea(dat1, dat2, dat3,
             wtp = WTP*yearindays,
             intlabels = c("All", "HIV positive", "HIV negative"),
             wtpNEG = "Y",
             SCALEcosts = FALSE,
             SCALEdays = FALSE,
             labelLong = FALSE,
             TITLE = "(a)",
             N = 769)

my.plot.bcea(dat1, dat2, dat3,
             wtp = WTP,
             intlabels = intlabels,
             contour = TRUE,
             wtpNEG = "Y")

my.plot.bcea(dat1, dat2, dat3,
             wtp = WTP*yearindays,
             intlabels = c("All", "HIV positive", "HIV negative"),
             contour = TRUE,
             wtpNEG = "Y",
             SCALEcosts = FALSE,
             SCALEdays = FALSE,
             labelLong = FALSE,
             TITLE = "(a)",
             N = 769)

my.plot.bcea(dat1, dat2, dat3,
             wtp = WTP,
             intlabels = intlabels,
             contour = TRUE,
             LEVELS = 0.5,
             wtpNEG = "Y")

my.plot.bcea(dat1, dat2, dat3,
             wtp = WTP*yearindays,
             intlabels = c("All", "HIV positive", "HIV negative"),
             contour = TRUE,
             LEVELS = 0.5,
             wtpNEG = "Y",
             SCALEcosts = FALSE,
             SCALEdays = FALSE,
             labelLong = FALSE,
             TITLE = "(a)",
             N = 769)
```

```{r CEAC, fig.width=9, fig.height=9, fig.keep='all'}

my.plot.ceac(dat1, dat2, dat3,
             intlabels = c("All", "HIV positive", "HIV negative"),
             labelLong = FALSE,
             TITLE = "(a)")

my.plot.ceac(dat1, dat2, dat3,
             intlabels = c("All", "HIV positive", "HIV negative"),
             labelLong = FALSE,
             TITLE = "(a)",
             SCALEcosts = FALSE,
             SCALEdays = FALSE,
             N = 769)

my.plot.ceac(dat1, dat2, dat3,
             intlabels = c("All", "HIV positive", "HIV negative"),
             labelLong = FALSE,
             TITLE = "(a)",
             SCALEcosts = FALSE,
             SCALEdays = FALSE,
             N = 769,
             CI = TRUE)
```
